##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  自定义项目配置 ###################
xncoding:
  socket-port: 9096    #socket端口
  ping-interval: 60000 #Ping消息间隔（毫秒）
  ping-timeout: 180000 #Ping消息超时时间（毫秒）

###################  项目启动端口  ###################
server.port: 9095

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/xncoding/jwt/dao/repository/mapping/*.xml
  typeAliasesPackage: >
    com.xncoding.jwt.api.model,
    com.xncoding.jwt.dao.entity,
    com.xncoding.jwt.common.dao.entity
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

###################  spring security配置  ###################
security:
  ignored: /static/**

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://123.207.66.156:3306/pos?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: ******
  thymeleaf:
    cache: false

###################  自定义项目配置 ###################
xncoding:
  apk-url-prefix: http://xncoding.net/files/ #APK文件访问URL前缀

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: E:/logs/app-manage-api.log

---

#####################################################################
########################  测试环境profile  ##########################
#####################################################################

spring:
  profiles: test
  datasource:
      url: jdbc:mysql://123.207.66.156:3306/pos?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: ******
  thymeleaf:
    cache: false

###################  自定义项目配置 ###################
xncoding:
  apk-url-prefix: https://show.xncoding.net/files/ #APK文件访问URL前缀

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /var/logs/app-manage-api.log
