##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  自定义项目配置 ###################
enzhico:
  kaptcha-open: true  #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session验证 (true/false)

###################  项目启动端口  ###################
server.port: 8092

###################  spring配置  ###################
spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

logging:
  level:
    ROOT: INFO
    com:
      enzhico: DEBUG
  file: E:/logs/aop.log

